import path from 'path'
import fs from 'fs'
import { AUTOGENERATED_FILE_HEADER } from '../constants/fileHeaders'
import { Stage } from '../models/stage.model'

interface CreateProjectOptions {
  projectName: string
  appId: string
  secretKey: string
  database: string
}

interface PackageJsonOptions {
  name: string
  version?: string
  description?: string
  author?: string
  license?: string
  dependencies?: Record<string, string>
  devDependencies?: Record<string, string>
}

type EnvOptions = {
  key: string;
  comment?: string;
  value: string;
}[];

/**
 * Service for creating files for a new project.
 */
export class FileCreator {
  constructor (
    private readonly APP_ID: string,
    private readonly PROJECT_DIR: string
  ) { }

  public createProject (options: CreateProjectOptions): void {
    // Check if project directory already exists
    if (fs.existsSync(this.PROJECT_DIR) && options.projectName !== '.') {
      throw new Error(`Project directory already exists: ${this.PROJECT_DIR}`)
    };

    // Create project directory
    this.createDir()

    const dependencies = this.getDatabaseDependencies(options.database)

    // Create root files
    this.createPackageJson({ 
      name: options.projectName,
      dependencies
    })
    this.createEnv([
      {
        key: 'APP_ID',
        comment: 'The ID of the Kottster app',
        value: options.appId,
      },
      {
        key: 'PORT',
        comment: 'Port to run the server on',
        value: '5480',
      },
      {
        key: 'SECRET_KEY',
        comment: 'Private key for obtaining a JWT secret during server startup',
        value: options.secretKey,
      },
    ])
    this.createGitIgnore()
    this.createDockerfile()
    this.createDir('src')
    this.createMainJs()
    this.createAppJs()
    this.createAdapterJs()

    // Create files for each stage
    Object.values(Stage).forEach((stage) => {
      // Create src/__generated__/<stage> directory
      this.createDir(`src/__generated__/${stage}`)

      // Create src/__generated__/index.js file
      this.createAutoImportsFile()
    })
  }

  private getDatabaseDependencies (database: string): Record<string, string> {
    if (!database) {
      throw new Error('Database is required. Use -db flag to specify the database to connect to')
    }
    
    switch (database) {
      case 'mysql':
      case 'mariadb':
        return { 'mysql2': '^3.9.7' }
      case 'postgres':
        return { 'pg': '^8.11.5' }
      case 'mssql':
        return { 'tedious': '^18.2.0' }
      default:
        throw new Error(`Unsupported database: ${database}`)
    }
  }

  /**
   * Create a package.json file
   */
  private createPackageJson (options: PackageJsonOptions) {
    const packageJsonPath = path.join(this.PROJECT_DIR, 'package.json')

    const packageJson = {
      name: options.name,
      type: 'module',
      version: options.version || '1.0.0',
      description: options.description || '',
      author: options.author || '',
      license: options.license || 'MIT',
      scripts: {
        start: 'kottster start src/main.js',
        postinstall: 'npm install @kottster/cli@^1.0.0 -g'
      },
      engines: {
        node: '>=16.0.0'
      },
      dependencies: {
        '@kottster/cli': process.env.KOTTSTER_CLI_DEP_VER ?? '^1.0.0',
        '@kottster/backend': process.env.KOTTSTER_BACKEND_DEP_VER ?? '^1.0.0',
        ...(options.dependencies ?? {}),
      },
      devDependencies: (options.devDependencies != null) || {}
    }
    const packageJsonContent = JSON.stringify(packageJson, null, 2)

    this.writeFile(packageJsonPath, packageJsonContent)
  }

  /**
   * Create a .env file
   */
  private createEnv (options: EnvOptions): void {
    const envPath = path.join(this.PROJECT_DIR, '.env')
    const envContent = options.map(({ key, comment, value }) => {
      return `${comment ? `# ${comment}\n` : ''}${key}=${value}`
    }).join('\n\n') + '\n';

    this.writeFile(envPath, envContent)
  }

  /**
   * Create a .gitignore file
   */
  private createGitIgnore (): void {
    const gitIgnorePath = path.join(this.PROJECT_DIR, '.gitignore')
    const gitIgnoreContent = ['node_modules', 'nbuild', 'npm-debug.log', '.DS_Store'].join('\n')

    this.writeFile(gitIgnorePath, gitIgnoreContent)
  }

  /**
   * Create a Dockerfile
   */
  private createDockerfile (): void {
    const dockerfilePath = path.join(this.PROJECT_DIR, 'Dockerfile')
    const dockerfileContent = `FROM node:18\n\nWORKDIR /usr/src/app\n\nCOPY package*.json ./\n\nRUN npm install\n\nCOPY . .\n\nRUN npm install @kottster/cli@^1.0.0 -g\n\nEXPOSE 5480\n\nCMD ["npm", "start"]\n\n`

    this.writeFile(dockerfilePath, dockerfileContent)
  }

  /**
   * Create a src/app.js file
   * @description This file creates the Kottster app for the specified stage
   */
  public createAppJs (): void {
    const appJsPath = path.join(this.PROJECT_DIR, 'src', 'app.js')

    let appJsContent = ''

    // Add imports
    appJsContent += 'import { createApp, getEnvOrThrow } from \'@kottster/backend\';\n\n'

    // Create app and export it
    appJsContent += `export const app = createApp({\n  appId: getEnvOrThrow('APP_ID'),\n  secretKey: getEnvOrThrow('SECRET_KEY')\n});\n\n`

    this.writeFile(appJsPath, appJsContent)
  }

  /**
   * Create a src/adapter.js file
   * @description This file is used to create an adapter for the app
   */
  public createAdapterJs (): void {
    const adapterJsPath = path.join(this.PROJECT_DIR, 'src', 'adapter.js')
    const adapterJsContent = 'export const adapter = null;\n\n'

    this.writeFile(adapterJsPath, adapterJsContent)
  }

  /**
   * Create a src/main.js file
   * @description This file is the entry point for the application
   */
  public createMainJs (): void {
    const mainJsPath = path.join(this.PROJECT_DIR, 'src', 'main.js')
    let mainJsContent = '';

    // Add imports
    mainJsContent += 'import \'./__generated__/index.js\';\n'
    mainJsContent += 'import { app } from \'./app.js\';\n'
    mainJsContent += 'import { adapter } from \'./adapter.js\';\n'
    mainJsContent += 'import { getEnvOrThrow } from \'@kottster/backend\';\n\n'

    // Set adapters for the app
    mainJsContent += 'app.setAdapter(adapter);\n\n'

    // Create express server and run it
    mainJsContent += `app.start(getEnvOrThrow('PORT') ?? 5480);\n\n`

    this.writeFile(mainJsPath, mainJsContent)
  }

  /**
   * Create a src/__generated__/index.js file
   * @description This file is used to auto-import all generated files
   */
  public createAutoImportsFile (): void {
    const indexJsPath = path.join(this.PROJECT_DIR, 'src/__generated__', 'index.js')
    const indexJsContent = AUTOGENERATED_FILE_HEADER + 'export {};\n\n'

    this.writeFile(indexJsPath, indexJsContent)
  }

  /**
   * Create a directory
   */
  private createDir (dirName?: string): void {
    // Skip if directory already exists
    if (dirName && fs.existsSync(path.join(this.PROJECT_DIR, dirName))) {
      return;
    }
    
    try {
      if (!dirName) {
        fs.mkdirSync(this.PROJECT_DIR, { recursive: true })
      } else {
        const dirPath = path.join(this.PROJECT_DIR, dirName)
        fs.mkdirSync(dirPath, { recursive: true })
      }
    } catch (error) {
      console.error(`Error creating ${dirName} directory:`, error)
    }
  }

  /**
   * Write content to a file
   */
  private writeFile (filePath: string, content: string): void {
    try {
      fs.writeFileSync(filePath, content)
    } catch (error) {
      console.error(`Error creating ${filePath} file:`, error)
    }
  }
}
